port:  5000
markdown: kramdown
name: "My Reps"
url: http://findmyreps.datamade.us
encoding: utf-8
timezone: America/New_York
description: "Enter your address to find and contact your state and federal elected representatives"
gems:
  - jekyll-redirect-from
google_api_key: AIzaSyAfh1uZMkK7XVSUEyvmPgSVU58kGjQh3iw
